security:
    encoders:
        AppBundle\Entity\Usat:
            algorithm: plaintext

    providers:
        chain_provider:
            chain:
                providers: [usat_provider]
        usat_provider:
            entity:
                class: AppBundle:Usat

    firewalls:
#        dev_exception:
#            pattern: ^/
#            security: false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern: ^/doc
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern:   ^/
            stateless: true
            lexik_jwt:
              throw_exceptions: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]