parameters:

services:
    app.api_exception.subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments:
            - "%kernel.debug%"
        tags:
            - { name: kernel.event_subscriber }

    api.event.jwt_created_listener:
        class: AppBundle\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
        arguments:
            - "@doctrine.orm.entity_manager"